package Model.enums;

public enum eventoModelo {

    TUTOR_AGREGADO,
    TUTOR_MODIFICADO,
    TUTOR_ELIMINADO,
    ESTUDIANTE_AGREGADO,
    ESTUDIANTE_MODIFICADO,
    ESTUDIANTE_ELIMINADO,
    RESERVA_CREADA,
    RESERVA_MODIFICADO,
    RESERVA_CANCELADA;
}
